[package]
name = "rustls-symcrypt"
authors = ["Microsoft"]
version = "0.3.0"
license = "Apache-2.0 OR ISC OR MIT"
description = "Implementation of rustls crypto provider model for SymCrypt"
edition.workspace = true
rust-version.workspace = true
homepage = "https://github.com/microsoft/SymCrypt"
repository = "https://github.com/microsoft/rustls-symcrypt"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = { version = "0.23.37", default-features = false, features = ["tls12", "std", "custom-provider"]}
# TEMPORARY: pin merged rust-symcrypt main until symcrypt 0.6.0 is published.
symcrypt = { version = "0.6.0", git = "https://github.com/microsoft/rust-symcrypt", rev = "7143e4c3bfe4e305b2518681c7752ae3d7b7ddbb" }

rustls-pki-types = "1.14.0"
pkcs1 = { version = "0.7.5", features = ["alloc"], default-features = false }
pkcs8 = "0.10"
sec1 = "0.8.0"
der = "0.8.0"

[features]
default = []
x25519 = []
pq = ["x25519"]
chacha = []

[dev-dependencies]
rustls-pemfile = "2"
webpki-roots = "1.0.6"
once_cell = "1.21.4"
