name: Cargo Fmt Check

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always        

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      # Checkout rust-symcrypt in a separate directory
      - name: Checkout rust-symcrypt
        uses: actions/checkout@v4
        with:
          repository: "microsoft/rust-symcrypt"
          path: "rust-symcrypt/rust-symcrypt"
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check
